<a href="https://colab.research.google.com/github/dana-prthv/LINYA-Internship/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/dana-prthv/LINYA-Internship/main/MostStreamedSpotifySongs2024.csv'
df = pd.read_csv(url, encoding='latin-1')

In [ ]:
df.head()

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",...,684,62.0,"17,598,718",114.0,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",...,3,67.0,"10,422,430",111.0,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",...,536,136.0,"36,321,847",172.0,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",...,"2,182",264.0,"24,684,248",210.0,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",...,1,82.0,"17,660,624",105.0,"4,493,884","7,006","207,179","457,017",NaN,1

In [ ]:
df.dtypes

Track                          object
Album Name                     object
Artist                         object
Release Date                   object
ISRC                           object
All Time Rank                  object
Track Score                   float64
Spotify Streams                object
Spotify Playlist Count         object
Spotify Playlist Reach         object
Spotify Popularity            float64
YouTube Views                  object
YouTube Likes                  object
TikTok Posts                   object
TikTok Likes                   object
TikTok Views                   object
YouTube Playlist Reach         object
Apple Music Playlist Count    float64
AirPlay Spins                  object
SiriusXM Spins                 object
Deezer Playlist Count         float64
Deezer Playlist Reach          object
Amazon Playlist Count         float64
Pandora Streams                object
Pandora Track Stations         object
Soundcloud Streams             object
Shazam Counts                  object
TIDAL Popularity              float64
Explicit Track                  int64
dtype: object

In [ ]:
df.shape

(4600, 29)

In [ ]:
df.isnull().sum()

Track                            0
Album Name                       0
Artist                           5
Release Date                     0
ISRC                             0
All Time Rank                    0
Track Score                      0
Spotify Streams                113
Spotify Playlist Count          70
Spotify Playlist Reach          72
Spotify Popularity             804
YouTube Views                  308
YouTube Likes                  315
TikTok Posts                  1173
TikTok Likes                   980
TikTok Views                   981
YouTube Playlist Reach        1009
Apple Music Playlist Count     561
AirPlay Spins                  498
SiriusXM Spins                2123
Deezer Playlist Count          921
Deezer Playlist Reach          928
Amazon Playlist Count         1055
Pandora Streams               1106
Pandora Track Stations        1268
Soundcloud Streams            3333
Shazam Counts                  577
TIDAL Popularity              4600
Explicit Track                   0
dtype: int64

In [ ]:
data=df.copy()
data = data.drop('TIDAL Popularity', axis=1)
data.columns

Index(['Track', 'Album Name', 'Artist', 'Release Date', 'ISRC',
       'All Time Rank', 'Track Score', 'Spotify Streams',
       'Spotify Playlist Count', 'Spotify Playlist Reach',
       'Spotify Popularity', 'YouTube Views', 'YouTube Likes', 'TikTok Posts',
       'TikTok Likes', 'TikTok Views', 'YouTube Playlist Reach',
       'Apple Music Playlist Count', 'AirPlay Spins', 'SiriusXM Spins',
       'Deezer Playlist Count', 'Deezer Playlist Reach',
       'Amazon Playlist Count', 'Pandora Streams', 'Pandora Track Stations',
       'Soundcloud Streams', 'Shazam Counts', 'Explicit Track'],
      dtype='object')

I dropped the column 'TIDAL Popularity' as all of its values were null.

In [ ]:
data=data.dropna(how='all')
data.shape

(4600, 28)

We can see that a row has been dropped as it had all null values.

In [ ]:
data['Amazon Playlist Count'].fillna('Unknown', inplace=True)

In [ ]:
data['Deezer Playlist Count'].ffill(inplace=True)

In [ ]:
data['Apple Music Playlist Count'].bfill(inplace=True)

In [ ]:
data['Spotify Popularity'].interpolate(method='linear', axis=0, limit=None, limit_direction='forward', limit_area=None, downcast=None, inplace=True)

In [ ]:
data.isnull().sum()

Track                            0
Album Name                       0
Artist                           5
Release Date                     0
ISRC                             0
All Time Rank                    0
Track Score                      0
Spotify Streams                113
Spotify Playlist Count          70
Spotify Playlist Reach          72
Spotify Popularity               0
YouTube Views                  308
YouTube Likes                  315
TikTok Posts                  1173
TikTok Likes                   980
TikTok Views                   981
YouTube Playlist Reach        1009
Apple Music Playlist Count       0
AirPlay Spins                  498
SiriusXM Spins                2123
Deezer Playlist Count            0
Deezer Playlist Reach          928
Amazon Playlist Count            0
Pandora Streams               1106
Pandora Track Stations        1268
Soundcloud Streams            3333
Shazam Counts                  577
Explicit Track                   0
dtype: int64

The columns 'Spotify Popularity' , 'Apple Music Playlist Count' , 'Deezer Playlist Count' , 'Amazon Playlist Count' have no null values after filling them.

**Filling missing data using Imputation :**

In [ ]:
df2=df.copy()
df2.drop('TIDAL Popularity', inplace=True, axis=1)

In [ ]:
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler, StandardScaler

In [ ]:
cols=['Spotify Popularity', 'Apple Music Playlist Count', 'Deezer Playlist Count', 'Amazon Playlist Count']

In [ ]:
imputer = SimpleImputer(strategy='mean')
df2[cols] = imputer.fit_transform(df2[cols])

In [ ]:
df2[cols].isnull().sum()

Spotify Popularity            0
Apple Music Playlist Count    0
Deezer Playlist Count         0
Amazon Playlist Count         0
dtype: int64

In [ ]:
df2[cols].head()

,Spotify Popularity,Apple Music Playlist Count,Deezer Playlist Count,Amazon Playlist Count
0,92.0,210.0,62.0,114.0
1,92.0,188.0,67.0,111.0
2,92.0,190.0,136.0,172.0
3,85.0,394.0,264.0,210.0
4,88.0,182.0,82.0,105.0

In [ ]:
df3=df.copy()
imputer = SimpleImputer(strategy='median')
df[cols] = imputer.fit_transform(df[cols])
df3[cols].isnull().sum()

Spotify Popularity             804
Apple Music Playlist Count     561
Deezer Playlist Count          921
Amazon Playlist Count         1055
dtype: int64

In [ ]:
df4=df.copy()
imputer = KNNImputer()
df[cols] = imputer.fit_transform(df[cols])
df4[cols].isnull().sum()

Spotify Popularity            0
Apple Music Playlist Count    0
Deezer Playlist Count         0
Amazon Playlist Count         0
dtype: int64

In [ ]:
encoder = LabelEncoder()
df['Soundcloud Streams'] = encoder.fit_transform(df['Soundcloud Streams'].fillna('unknown'))
df['Soundcloud Streams'].isnull().sum()

0

In [ ]:
url = 'https://raw.githubusercontent.com/dana-prthv/LINYA-Internship/main/Sales.csv'
df = pd.read_csv(url)

In [ ]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [ ]:
df['Product Category'].unique()

array(['Electronics', 'Home Appliances', 'Clothing', 'Books',
       'Beauty Products', 'Sports'], dtype=object)

In [ ]:
df['Payment Method'].unique()

array(['Credit Card', 'PayPal', 'Debit Card'], dtype=object)

In [ ]:
df['Region'].unique()

array(['North America', 'Europe', 'Asia'], dtype=object)

The above mentioned columns have these unique values.

In [ ]:
one_hot_cols = ['Product Category', 'Region', 'Payment Method']
enco = pd.get_dummies(df, columns=one_hot_cols)
enco.head()

,Transaction ID,Date,Product Name,Units Sold,Unit Price,Total Revenue,Product Category_Beauty Products,Product Category_Books,Product Category_Clothing,Product Category_Electronics,Product Category_Home Appliances,Product Category_Sports,Region_Asia,Region_Europe,Region_North America,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,10001,2024-01-01,iPhone 14 Pro,2,999.99,1999.98,False,False,False,True,False,False,False,False,True,True,False,False
1,10002,2024-01-02,Dyson V11 Vacuum,1,499.99,499.99,False,False,False,False,True,False,False,True,False,False,False,True
2,10003,2024-01-03,Levi's 501 Jeans,3,69.99,209.97,False,False,True,False,False,False,True,False,False,False,True,False
3,10004,2024-01-04,The Da Vinci Code,4,15.99,63.96,False,True,False,False,False,False,False,False,True,True,False,False
4,10005,2024-01-05,Neutrogena Skincare Set,1,89.99,89.99,True,False,False,False,False,False,False,True,False,False,False,True

In [ ]:
le= LabelEncoder()
enco['Product Name'] = le.fit_transform(df['Product Name'])
enco['Product Name'].head()

0    230
1     59
2    115
3    182
4    131
Name: Product Name, dtype: int64

**Min Max Scaling :**

In [ ]:
mms = MinMaxScaler()
numerical_columns = ['Units Sold', 'Unit Price', 'Total Revenue']
enco[numerical_columns] = mms.fit_transform(df_encoded[numerical_columns])

In [ ]:
enco.head()

,Transaction ID,Date,Product Name,Units Sold,Unit Price,Total Revenue,Product Category_Beauty Products,Product Category_Books,Product Category_Clothing,Product Category_Electronics,Product Category_Home Appliances,Product Category_Sports,Region_Asia,Region_Europe,Region_North America,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,10001,2024-01-01,230,0.111111,0.255167,0.512003,False,False,False,True,False,False,False,False,True,True,False,False
1,10002,2024-01-02,59,0.000000,0.126747,0.126747,False,False,False,False,True,False,False,True,False,False,False,True
2,10003,2024-01-03,115,0.222222,0.016307,0.052259,False,False,True,False,False,False,True,False,False,False,True,False
3,10004,2024-01-04,182,0.333333,0.002437,0.014758,False,True,False,False,False,False,False,False,True,True,False,False
4,10005,2024-01-05,131,0.000000,0.021443,0.021443,True,False,False,False,False,False,False,True,False,False,False,True

I used Min-Max scaler to scale down the values of the columns 'Units Sold' , 'Unit Price'& 'Total Revenue' as it seemed apt for its values being in the range of 0 to 1.

**Standard Scaling :**

In [ ]:
from sklearn.preprocessing import StandardScaler
cols=['Spotify Popularity', 'Apple Music Playlist Count', 'Deezer Playlist Count', 'Amazon Playlist Count']

In [ ]:
sc=StandardScaler()
cpy=df2.copy()
cpy[cols] = sc.fit_transform(cpy[cols])
cpy[cols].head()

,Spotify Popularity,Apple Music Playlist Count,Deezer Playlist Count,Amazon Playlist Count
0,1.938396,2.316064,0.611749,3.886088
1,1.938396,1.988172,0.714775,3.754581
2,1.938396,2.017981,2.136534,6.428563
3,1.462272,5.058435,4.774000,8.094322
4,1.666325,1.898747,1.023853,3.491566

Now using Standard Scaling the values for these 4 columns have been scaled down to have a mean of 0 and a standard deviation of 1.